openapi: 3.0.1
info:
  title: Betting.API
  version: '1.0'
paths:
  /api/Matches:
    post:
      tags:
        - Matches
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MatchDTO'
          text/json:
            schema:
              $ref: '#/components/schemas/MatchDTO'
          application/*+json:
            schema:
              $ref: '#/components/schemas/MatchDTO'
      responses:
        '200':
          description: Success
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
    put:
      tags:
        - Matches
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MatchDTO'
          text/json:
            schema:
              $ref: '#/components/schemas/MatchDTO'
          application/*+json:
            schema:
              $ref: '#/components/schemas/MatchDTO'
      responses:
        '200':
          description: Success
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /api/Matches/{id}:
    get:
      tags:
        - Matches
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
    delete:
      tags:
        - Matches
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /api/Matches/matchOdds:
    post:
      tags:
        - Matches
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/MatchOddDTO'
          text/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/MatchOddDTO'
          application/*+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/MatchOddDTO'
      responses:
        '200':
          description: Success
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /api/Matches/MatchOdds/{matchId}:
    get:
      tags:
        - Matches
      parameters:
        - name: matchId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /api/Matches/MatchOdds:
    put:
      tags:
        - Matches
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MatchOddDTO'
          text/json:
            schema:
              $ref: '#/components/schemas/MatchOddDTO'
          application/*+json:
            schema:
              $ref: '#/components/schemas/MatchOddDTO'
      responses:
        '200':
          description: Success
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /api/Matches/matchOdds/{id}:
    delete:
      tags:
        - Matches
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
components:
  schemas:
    MatchDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
        description:
          type: string
          nullable: true
        matchDate:
          type: string
          format: date-time
        matchTime:
          type: string
          format: date-time
        teamA:
          type: string
          nullable: true
        teamB:
          type: string
          nullable: true
        sport:
          type: string
          nullable: true
        matchOdds:
          type: array
          items:
            $ref: '#/components/schemas/MatchOddDTO'
          nullable: true
      additionalProperties: false
    MatchOddDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
        matchId:
          type: integer
          format: int32
        specifier:
          type: string
          nullable: true
        odd:
          type: number
          format: double
      additionalProperties: false
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
      additionalProperties: {}
