---
openapi: 3.0.0
info:
  title: Betting API
  description: API to manage matches and their odds.
  version: "1.0"
servers:
- url: /
paths:
  /matches:
    post:
      description: Create match entity in Database
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Match'
        required: true
      responses:
        "200":
          description: Match created successfully
  /matches/matchOdds:
    post:
      description: Create match odds entity in Database
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MatchOdds'
        required: true
      responses:
        "200":
          description: Match odd created successfully
  /matches/{id}:
    get:
      description: Obtain information about specific match
      parameters:
      - name: id
        in: path
        description: The match ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          example: 2
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Match'
    put:
      description: Update a match
      parameters:
      - name: id
        in: path
        description: The match ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          example: 12
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Match'
        required: true
      responses:
        "200":
          description: Match updated successfully
    delete:
      description: Delete match entity from Database
      parameters:
      - name: id
        in: path
        description: The entity ID for deletion
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          example: 5
      responses:
        "200":
          description: Successfully deleted
  /matches/matchOdds/{id}:
    get:
      description: Obtaion information about specific match odds
      parameters:
      - name: id
        in: path
        description: The match odd ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          example: 3
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatchOdds'
    put:
      description: Update the Match Odds
      parameters:
      - name: id
        in: path
        description: The match odd ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          example: 10
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MatchOdds'
        required: true
      responses:
        "200":
          description: Match odds updated successfully
    delete:
      description: Delete match odds entity from Database
      parameters:
      - name: id
        in: path
        description: The entity ID from deletion
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          example: 5
      responses:
        "200":
          description: Successfully deleted
components:
  schemas:
    Interaction:
      required:
      - id
      type: object
      properties:
        id:
          type: integer
          format: int32
    Match:
      properties:
        id:
          type: integer
          example: 2
        description:
          type: string
          example: OSFP-PAO
        matchDate:
          type: string
          format: date
          example: 2020-12-18
        matchTime:
          type: string
          example: 12:00
        teamA:
          type: string
          example: OSFP
        teamB:
          type: string
          example: PAO
        sport:
          type: integer
          example: 1
      description: Model which contain Match info
    MatchOdds:
      properties:
        id:
          type: integer
          example: 5
        matchId:
          type: integer
          example: 4
        specifier:
          type: string
          example: X
        odd:
          type: number
          format: float
          example: 1.85
      description: Model which contain Match Odds info
