openapi: 3.0.1
info:
  title: Betting.API
  version: '1.0'
paths:
  /api/Matches:
    post:
      tags:
        - Matches
      summary: Create new Match.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MatchDTO'
          text/json:
            schema:
              $ref: '#/components/schemas/MatchDTO'
          application/*+json:
            schema:
              $ref: '#/components/schemas/MatchDTO'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/MatchResponseDTO'
            application/json:
              schema:
                $ref: '#/components/schemas/MatchResponseDTO'
            text/json:
              schema:
                $ref: '#/components/schemas/MatchResponseDTO'
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
    put:
      tags:
        - Matches
      summary: Update Match.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MatchDTO'
          text/json:
            schema:
              $ref: '#/components/schemas/MatchDTO'
          application/*+json:
            schema:
              $ref: '#/components/schemas/MatchDTO'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/MatchResponseDTO'
            application/json:
              schema:
                $ref: '#/components/schemas/MatchResponseDTO'
            text/json:
              schema:
                $ref: '#/components/schemas/MatchResponseDTO'
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /api/Matches/{id}:
    get:
      tags:
        - Matches
      summary: Get Match from Database.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/MatchResponseDTO'
            application/json:
              schema:
                $ref: '#/components/schemas/MatchResponseDTO'
            text/json:
              schema:
                $ref: '#/components/schemas/MatchResponseDTO'
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
    delete:
      tags:
        - Matches
      summary: Delete Match from Database.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/MatchResponseDTO'
            application/json:
              schema:
                $ref: '#/components/schemas/MatchResponseDTO'
            text/json:
              schema:
                $ref: '#/components/schemas/MatchResponseDTO'
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /api/Matches/matchOdds:
    post:
      tags:
        - Match Odds
      summary: Create Match Odd.
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/MatchOddDTO'
          text/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/MatchOddDTO'
          application/*+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/MatchOddDTO'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/MatchOddsListResponseDTO'
            application/json:
              schema:
                $ref: '#/components/schemas/MatchOddsListResponseDTO'
            text/json:
              schema:
                $ref: '#/components/schemas/MatchOddsListResponseDTO'
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /api/Matches/MatchOdds/{matchId}:
    get:
      tags:
        - Match Odds
      summary: Get Match Odds.
      parameters:
        - name: matchId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/MatchOddsListResponseDTO'
            application/json:
              schema:
                $ref: '#/components/schemas/MatchOddsListResponseDTO'
            text/json:
              schema:
                $ref: '#/components/schemas/MatchOddsListResponseDTO'
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /api/Matches/MatchOdds:
    put:
      tags:
        - Match Odds
      summary: Update Match Odds.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MatchOddDTO'
          text/json:
            schema:
              $ref: '#/components/schemas/MatchOddDTO'
          application/*+json:
            schema:
              $ref: '#/components/schemas/MatchOddDTO'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/MatchOddsResponseDTO'
            application/json:
              schema:
                $ref: '#/components/schemas/MatchOddsResponseDTO'
            text/json:
              schema:
                $ref: '#/components/schemas/MatchOddsResponseDTO'
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /api/Matches/matchOdds/{id}:
    delete:
      tags:
        - Match Odds
      summary: Delete Match Odd from Database.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/MatchOddsResponseDTO'
            application/json:
              schema:
                $ref: '#/components/schemas/MatchOddsResponseDTO'
            text/json:
              schema:
                $ref: '#/components/schemas/MatchOddsResponseDTO'
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
components:
  schemas:
    Match:
      type: object
      properties:
        id:
          type: integer
          format: int32
        description:
          type: string
          nullable: true
        matchDate:
          type: string
          format: date-time
        matchTime:
          type: string
          format: date-time
        teamA:
          type: string
          nullable: true
        teamB:
          type: string
          nullable: true
        sport:
          $ref: '#/components/schemas/SportValues'
        matchOdds:
          type: array
          items:
            $ref: '#/components/schemas/MatchOdds'
          nullable: true
      additionalProperties: false
    MatchDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
        description:
          type: string
          nullable: true
        matchDate:
          type: string
          format: date-time
        matchTime:
          type: string
          format: date-time
        teamA:
          type: string
          nullable: true
        teamB:
          type: string
          nullable: true
        sport:
          type: string
          nullable: true
        matchOdds:
          type: array
          items:
            $ref: '#/components/schemas/MatchOddDTO'
          nullable: true
      additionalProperties: false
    MatchOddDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
        matchId:
          type: integer
          format: int32
        specifier:
          type: string
          nullable: true
        odd:
          type: number
          format: double
      additionalProperties: false
    MatchOdds:
      type: object
      properties:
        id:
          type: integer
          format: int32
        matchId:
          type: integer
          format: int32
        specifier:
          type: string
          nullable: true
        odd:
          type: number
          format: double
      additionalProperties: false
    MatchOddsListResponseDTO:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/MatchOdds'
          nullable: true
        errorMessages:
          type: array
          items:
            type: string
          nullable: true
        message:
          type: string
          nullable: true
      additionalProperties: false
    MatchOddsResponseDTO:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/MatchOdds'
        errorMessages:
          type: array
          items:
            type: string
          nullable: true
        message:
          type: string
          nullable: true
      additionalProperties: false
    MatchResponseDTO:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Match'
        errorMessages:
          type: array
          items:
            type: string
          nullable: true
        message:
          type: string
          nullable: true
      additionalProperties: false
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
      additionalProperties: {}
    SportValues:
      enum:
        - 1
        - 2
      type: integer
      format: int32
